services:  
  postgres_new:
    image: postgres:14-alpine
    ports:
      - 5433:5432  # Different host port to avoid conflicts
    volumes:
      - ~/apps/postgres_new:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=website_db
    networks:
      - db_network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://username:password@postgres_new:5432/website_db
    depends_on:
      - postgres_new
    volumes:
      - .:/app  # This line mounts the current directory to /app in the container
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network: