# Generated by Django 5.1.1 on 2024-10-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_userinfo_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
