# Generated by Django 5.1.1 on 2024-10-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_userinfo_tryingout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tryingagain',
            field=models.CharField(default='test!', max_length=50),
            preserve_default=False,
        ),
    ]
