# Generated by Django 5.1.1 on 2024-11-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_userinfo_tryingagain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
