# Generated by Django 5.1.1 on 2024-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_userinfo_age_remove_userinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='abc@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='experience_abroad',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='graduation_time',
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='highest_education',
            field=models.CharField(default='masters', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='highest_title_achieved',
            field=models.CharField(default='highesttitle', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='job_position_wanted',
            field=models.CharField(default='lawyer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='major',
            field=models.CharField(default='engineering', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='jun', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='political_info',
            field=models.CharField(default='left', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(default='ex', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='target_working_place',
            field=models.CharField(default='berlin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='type_of_job',
            field=models.CharField(default='engineer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='university',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
