# Generated by Django 5.1.1 on 2024-11-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_userinfo_birth_date_and_more'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='userinfo',
    #         old_name='birth_date',
    #         new_name='birth_datee',
    #     ),
    #     migrations.RenameField(
    #         model_name='userinfo',
    #         old_name='graduation_time',
    #         new_name='graduation_timee',
    #     ),
    # ]
