# Generated by Django 5.1.1 on 2024-11-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_birth_date_userinfo_birth_datee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='graduation_time',
            field=models.DateField(default="2000-01-01"),
        ),
    ]
