# Generated by Django 5.1.2 on 2024-11-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_birth_date_userinfo_birth_datee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='graduation_time',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='time_of_graduation',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
