# Generated by Django 5.1.1 on 2024-11-01 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_userinfo_birth_datee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='graduation_time',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
