# Generated by Django 5.1.2 on 2024-11-11 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_rename_birth_date_userinfo_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='major_type',
            field=models.CharField(default='engineering', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='major',
            field=models.CharField(default='engineering', max_length=100),
        ),
    ]
