# Generated by Django 5.1.2 on 2024-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_userinfo_major_type_alter_userinfo_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='major_type',
            field=models.CharField(max_length=100),
        ),
    ]
