# Generated by Django 5.1.2 on 2024-11-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_userinfo_major_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='major',
            field=models.CharField(max_length=100),
        ),
    ]
