# Generated by Django 5.1.1 on 2024-11-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_userinfo_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='graduation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
