# Generated by Django 5.1.1 on 2024-11-01 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_userinfo_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='graduation_time',
            new_name='time_of_graduation',
        ),
    ]
